# Generated by Django 5.0.2 on 2024-04-22 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='leader', to='accounts.customuser'),
            preserve_default=False,
        ),
    ]
