# Generated by Django 5.0.4 on 2024-04-26 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_room_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='active',
            new_name='is_active',
        ),
    ]
