# Generated by Django 5.0.4 on 2024-04-26 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_rename_active_room_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='point',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
