# Generated by Django 5.0.4 on 2024-08-07 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_comment_point_delete_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='point',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
