name: reservation_app_test
on: workflow_dispatch
jobs:
    reservation_app_test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                    python-version: '3.12'
                    architecture: 'x64'
            - name: dependencies
              run: pip install -r requirements.txt
            - name: test
              run: python3 manage.py test reservation
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              run: echo "deploy"